### ISSUE TITLE
Request for Discord Releases to be Placed on Github

### ISSUE THREAD

**Issue by lonegraywolf2000** [brianmcn/Zelda1RandoTools#16]
I admit I'm confused by the documentation and github releases page. The github release page is up to v1.1, but the documentation mentions that the latest version, v1.2, requires joining a specific discord. I left the aforementioned discord almost two years ago, and I don't think it makes sense to join just to grab a program and leave. Heck, I don't even know if I'm allowed back in that discord.

Are you able to provide the releases on github again? If you are unable to, can you at least state why you cannot?

**Comment by JerryArr** [comment]
Seconding this request. This would be particularly helpful for people who are in a lot of Discord servers and don't want to keep track of another, or for shy people.

**Comment by brianmcn** [comment]
Ok, I updated the docs with a link to download it directly off github, now that development has slowed/stopped.
